# Yaml file to create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirst-deployment
  labels:
    app: simple-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: myfirst-container
        image: summit2019/welcome:summit01
        ports:
        - containerPort: 80
