apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: docker-source1
        type: git
    params:
      - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build
      - name: pathToContext
        type: string
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      - name: tag
        type: string
        description: Image tag in dockerhub
  outputs:
    resources:
      - name: builtImage1
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.13.0
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage1.url):$(inputs.params.tag)
        - --context=$(inputs.params.pathToContext)
