apiVersion: cloner.example.com/v1alpha1
kind: Cloner
metadata:
  name: example
spec:
  clones: 10
  selector:
    matchLabels:
      app: summit
  template:
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: Simple-Web
        image: kvenkata986/welcome:1.0
        command:
        - "sleep"
        - "3600"
