apiVersion: cloner.example.com/v1alpha1
kind: Cloner
metadata:
  name: example
spec:
  clones: 10
  selector:
    matchLabels:
      app: summit
  template:
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: busybox
        image: busybox
        command:
        - "sleep"
        - "3600"
